package com.tambapps.analyzer

enum TokenType {
    IDENTIFIER, CONSTANT,
    PLUS, MINUS, DIVIDE, MULTIPLY, POWER, MODULO,
    PARENT_OPEN, PARENT_CLOSE, //TODO
    ACCOLADE_OPEN, ACCOLADE_CLOSE //TODO
}